### ISSUE TITLE
Exported HTML game won't start

### ISSUE THREAD

**Issue by devdouglasonofre** [Lyatus/raccoon#3]
### Subject of the issue
After exporting the game as a HTML file, I try to run it for testing but with no success.

### Your environment
* Raccoon commit a2befa1dde203d49f42c9523934f4ca2018ea2c1
* Google Chrome Windows 10 64bit 91.0.4472.124

### Steps to reproduce
Under the 'File' menu Item, select 'Export' then 'HTML'. With the HTML generated and saved, run it by opening it on your browser.

### Expected behaviour
The game should start normally.

### Actual behaviour
The game won't start.

### Log 
```
game.html:735 Uncaught (in promise) TypeError: Cannot read property 'rom' of undefined
    at rcn_canvas.upload_palette (game.html:735)
    at new rcn_canvas (game.html:729)
    at new rcn_vm (game.html:1080)
    at rcn_start_game_mode (game.html:902)
    at game.html:173
```

### Code for the game
```
var x = 25
var y = 25
function init(){

}

function update(f, d){
  if(btn(0, 0)){
    x = x- 1
  }
  if(btn(1, 0)){
    x = x+1
  }
  if(btn(2, 0)){
    y = y-1
  }
  if(btn(3, 0)){
    y = y+1
  }
}

function draw(){
  cls(c=0)
  circfill(x, y, 20, 4)
}
```

**Comment by devdouglasonofre** [comment]
Update: running it by using a web server won't help either.

**Comment by lut0pia** [comment]
Thank you for reporting this! I'm at work currently but I'll be taking a look at it later today.

**Comment by lut0pia** [comment]
Alright it should work fine now with https://github.com/Lyatus/raccoon/commit/fe1fa2125b96ffbfeb65c4e70e597d0f2297b9d0. Do tell me if you encounter other problems!
